#!/usr/bin/env -S just --justfile

alias d := dev
alias t := test

# List available commands.
_default:
    just --list --unsorted

dev:
    cargo watch -x clippy -x run

# Format the codebase.
fmt:
    cargo fmt --all

# Check is the codebase properly formatted.
fmt-check:
    cargo fmt --all -- --check

# Lint the codebase.
lint:
    cargo clippy

# Test the codebase.
test:
    cargo test

# Tasks to make the code-base comply with the rules. Mostly used in git hooks.
comply: fmt lint test

# Check if the repository comply with the rules and ready to be pushed.
check: fmt-check lint test

# Local Variables:
# mode: makefile
# End:
# vim: set ft=make :
