#!/usr/bin/env -S just --justfile

alias d := dev
alias t := test

# List available commands.
_default:
    just --list --unsorted

# Setup the repository.
setup:
    pnpm i
    pnpx husky install

# Develop the app.
dev:
    pnpm dev

# Lint the codebase.
lint:
    pnpm run lint
    pnpm run type-check

# Format the codebase.
fmt: lint
    dprint fmt --config configs/dprint.json

# Check is the codebase properly formatted.
fmt-check: lint
    dprint check --config configs/dprint.json

# Test the codebase.
test:
    pnpm run test

# Tasks to make the code-base comply with the rules. Mostly used locally or in git hooks.
comply: fmt lint test

# Check if the repository comply with the rules. Mostly used in CI.
check: fmt-check lint test

# Create a new release. Example `just release v2.2.0`
release version:
    bash scripts/release.sh {{ version }}

# Check dependencies health.
up:
    ncu
