#!/usr/bin/env -S just --justfile

alias r := run

# List available commands.
_default:
    just --list --unsorted

# Setup the repository.
setup:
    pnpm i

# Tasks to make the code-base comply with the rules. Mostly used locally or in git hooks.
comply: fmt lint
    pnpm run check

# Check if the repository comply with the rules. Mostly used in CI.
check: fmt-check lint
    pnpm run check

# Develop the app.
run:
    pnpm run dev

# Format the codebase.
fmt:
    pnpm run format

# Check is the codebase properly formatted.
fmt-check:

# Lint the codebase.
lint:
    pnpm run lint
    pnpm run check

# Check dependencies health. Pass `--write` to uppgrade dependencies.
[unix]
up arg="":
    #!/usr/bin/env bash
    if [ "{{ arg }}" = "--write" ]; then
        taze --write
    else
        taze
    fi;

