#!/usr/bin/env -S just --justfile

alias d := dev

# List available commands.
_default:
    just --list --unsorted

# Setup the repository.
setup:
    pnpm i

# Develop the app.
dev:
    pnpm run dev

# Lint the codebase.
lint:
    pnpm lint

# Format the codebase.
fmt:
    pnpx prettier --config configs/prettier.config.cjs --ignore-path configs/prettierignore --write . --plugin-search-dir=. ./**/*.svelte

# Check is the codebase properly formatted.
fmt-check:
    pnpx prettier --config configs/prettier.config.cjs --ignore-path configs/prettierignore --check . --plugin-search-dir=. ./**/*.svelte

# Tasks to make the code-base comply with the rules. Mostly used locally or in git hooks.
comply: fmt lint
    pnpm run check

# Check if the repository comply with the rules. Mostly used in CI.
check: fmt-check lint
    pnpm run check

#

# Check dependencies health.
up:
    ncu

# Local Variables:
# mode: makefile
# End:
# vim: set ft=make :
