/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Head: typeof import('@vueuse/head')['Head']
    'IEosIcons:bubbleLoading': typeof import('~icons/eos-icons/bubble-loading')['default']
    'ITabler:language': typeof import('~icons/tabler/language')['default']
    'ITabler:menu2': typeof import('~icons/tabler/menu2')['default']
    'ITabler:moodSad': typeof import('~icons/tabler/mood-sad')['default']
    'ITabler:search': typeof import('~icons/tabler/search')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PokemonCard: typeof import('./src/components/PokemonCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
