[package]
name = "backend"
version = "0.1.1"
authors = ["azzamsa <vcs@azzamsa.com>"]
categories = ["web-programming"]
edition = "2021"
exclude = ["/README.md"]
keywords = ["boilerplate"]
license = "MIT"
repository = "https://github.com/azzamsa/tin"
description = "Rust GraphQL Template"

[dependencies]
# web server
axum = "0.6.4"
hyper = "0.14"
tokio = { version = "1.24", features = ["macros", "rt-multi-thread"] }

# GraphQL
async-graphql = { version = "5.0", features = ["uuid", "chrono"] }
async-graphql-axum = "5.0"

# Rest
utoipa = { version = "3.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "3.0", features = ["axum"] }

# log
env_logger = "0.10"
log = "0.4"

dotenv = "0.15"
nrot = "2.0.0"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"

[dev-dependencies]
anyhow = "1.0"
cynic = "2.2"
hyper = { version = "0.14.23", features = ["full"] }
mime = "0.3.16"
serde = { version = "1.0", features = ["derive"] }
tower = { version = "0.4", features = ["util"] }
