#! /usr/bin/env bash

help () {
    cat << EOF

Usage: make [options]

Options:

    verify          Make the codebase adhere to the rules
    is_verified     Check if the codebase adhere to the rules

EOF

}

verify () {
    echo "::: Format"
    black src/

    echo "::: Lint"
    pylint src/

    echo "::: Test"
    pytest src/
    mypy src/

    echo "::: Count coverage"
    coverage run -m pytest src/
    coverage report -m

}

is_verified () {
    echo "::: Formatting check"
    black --check src/

    echo "::: Linting check"
    pylint src/
    mypy src/

    echo "::: Testing check"
    pytest src/

}



if [ ! -n "$1" ]
then
    help
    exit
fi

while [ -n "$1" ]; do

    case "$1" in

        verify) verify ;;
        is_verified) is_verified ;;
        help) help ;;

    esac
    break

done

