#!/usr/bin/env -S just --justfile

shebang := if os() == 'windows' { 'powershell.exe' } else { '/usr/bin/sh' }

set dotenv-load := true

alias d := dev
alias r := run
alias f := fmt
alias l := lint
alias t := test

# List available commands.
_default:
    just --list --unsorted

# Setup the repository
setup:
    cargo nextest --version || cargo install --locked cargo-nextest
    cargo watch --version || cargo install cargo-watch

# Develop the app.
dev:
    cargo watch -x clippy

# Develop the app.
run:
    cargo run

# Format the codebase.
fmt:
    cargo fmt --all
    dprint fmt --config .config/dprint.json

# Check is the codebase properly formatted.
fmt-check:
    cargo fmt --all -- --check

# Lint the codebase.
lint:
    cargo clippy --locked --all-targets --all-features

# Check the documentation.
_doc-check:
    cargo doc --all-features --no-deps

# Run the unit tests.
_unit-test:
    cargo nextest run --lib

# Test the codebase.
test:
    cargo nextest run --all-targets

# Tasks to make the code-base comply with the rules. Mostly used in git hooks.
comply: fmt lint test

# Check if the repository comply with the rules and ready to be pushed.
check:  fmt-check lint test _doc-check

# Check dependencies health. Pass `--write` to uppgrade dependencies.
up arg="":
    #!{{ shebang }}
    if [ "{{ arg }}" = "--write" ]; then
    	cargo upgrade
    	cargo update
    else
    	cargo udeps
        cargo outdated --root-deps-only
    fi;
