# Dockerfile.4

FROM rust:1.70.0-alpine3.18 as builder
RUN apk add musl-dev
WORKDIR app
COPY . .
RUN cargo build --release

FROM alpine:3.18.0
COPY --from=builder /app/target/release/hello /
CMD ["./hello"]
