# Dockerfile.5

FROM rust:1.70.0-slim-bullseye as builder
WORKDIR app
COPY . .
RUN cargo build --release

FROM gcr.io/distroless/cc-debian11
COPY --from=builder /app/target/release/hello /
CMD ["./hello"]
