[package]
name = "frontend"
version = "1.0.8"
edition = "2021"

[dependencies]
cynic = "1.0.0"
dioxus = { version = "0.2.3", features = ["web"] }
reqwest = { version = "0.11.11", features = ["json"] }
serde = "1.0.140"
