[package]
name = "frontend"
version = "1.0.8"
edition = "2021"

[dependencies]
cynic = "2.2"
dioxus = { version = "0.2", features = ["web"] }
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0"
