[package]
name = "pokedex"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.6.13", features = ["csr", "nightly"] }
leptos_router = { version = "0.6.13", features = ["csr"] }
