repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        types: [python]
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
  - repo: 'https://github.com/psf/black'
    rev: 21.4b0
    hooks:
      - id: black
        files: src/
  - repo: 'https://github.com/PyCQA/isort'
    rev: 5.8.0
    hooks:
      - id: isort
        files: src/
        args:
          - '--profile=black'
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        files: src/
        types: [python]
        args:
          [
            "--rcfile=pylintrc",
          ]
