name: Caesar Dioxus (CI)

env:
  MIN_SUPPORTED_RUST_VERSION: "1.77.0"

on:
  push:
    paths:
      -  src/caesars/web/frontend/dioxus/**
      - .github/workflows/caesars.yml
      - .github/workflows/caesars_dioxus.yml
  pull_request:
    paths:
      -  src/caesars/web/frontend/dioxus/**
      - .github/workflows/caesars.yml
      - .github/workflows/caesars_dioxus.yml

defaults:
  run:
    working-directory: src/caesars/web/frontend/dioxus

jobs:
  code_quality:
    name: Code quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@dprint
      - uses: taiki-e/install-action@v2
        with:
          tool: dioxus-cli

      - name: Run check
        run: just check


  min_version:
    name: Minimum supported rust version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install rust toolchain (v${{ env.MIN_SUPPORTED_RUST_VERSION }})
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.MIN_SUPPORTED_RUST_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@dprint

      - name: Run test
        run:  just test

  build:
    name: ${{ matrix.job.os }} (${{ matrix.job.target }})
    runs-on: ${{ matrix.job.os }}

    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest, target: wasm32-unknown-unknown   }

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.job.target }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install JS dependencies
        run: |
          pnpm i

      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@v2
        with:
          tool: dioxus-cli

      - name: Show version information
        shell: bash
        run: |
          cargo -V
          rustc -V

      - name: Run build
        run:  just build

      - name: Run test
        run:  just test
