name: Caesar Vue (CI)

on:
  push:
    paths:
      -  src/caesars/web/frontend/vue/**
      - .github/workflows/caesars.yml
      - .github/workflows/caesars_vue.yml
  pull_request:
    paths:
      -  src/caesars/web/frontend/vue/**
      - .github/workflows/caesars.yml
      - .github/workflows/caesars_vue.yml

defaults:
  run:
    working-directory: src/caesars/web/frontend/vue

jobs:
  ci:
    name: Code quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: just check
