name: Caesar (CI)

on:
  push:
    paths:
      -  src/caesars/**
      - .github/workflows/caesars.yml
  pull_request:
    paths:
      -  src/caesars/**
      - .github/workflows/caesars.yml

defaults:
  run:
    working-directory: src/caesars

jobs:
  code_quality:
    name: Code quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install latest just release
        uses: taiki-e/install-action@just

      - name: Install latest dprint release
        uses: taiki-e/install-action@dprint

      - name: Check if the repository comply with the rules
        run:  just check
