name: Caesar SvelteKit (CI)

on:
  push:
    paths:
      -  src/caesars/web/frontend/sveltekit/**
      - .github/workflows/caesars.yml
      - .github/workflows/caesars_sveltekit.yml
  pull_request:
    paths:
      -  src/caesars/web/frontend/sveltekit/**
      - .github/workflows/caesars.yml
      - .github/workflows/caesars_sveltekit.yml

defaults:
  run:
    working-directory: src/caesars/web/frontend/sveltekit

jobs:
  ci:
    name: Code quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install latest just release
        uses: taiki-e/install-action@just

      - name: Install local dependencies
        run: |
          pnpm i

      - name: Lint
        run: |
          just check
