name: Caesar Vue (CI)

on:
  push:
    paths:
      -  src/caesars/frontend/vue/**
      - .github/workflows/caesars.yml
      - .github/workflows/caesars_vue.yml
  pull_request:
    paths:
      -  src/caesars/frontend/vue/**
      - .github/workflows/caesars.yml
      - .github/workflows/caesars_vue.yml

defaults:
  run:
    working-directory: src/caesars/frontend/svelte

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install latest just release
        uses: extractions/setup-just@v1

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install local dependencies
        run: |
          pnpm i

      - name: Lint
        run: |
          just check
