name: Keywords (CI)

on:
  push:
    paths:
      -  src/keywords/**
      - .github/workflows/keywords.yml
  pull_request:
    paths:
      -  src/keywords/**
      - .github/workflows/keywords.yml

defaults:
  run:
    working-directory: src/keywords

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install latest dprint release
        uses: taiki-e/install-action@v1
        with:
          tool: dprint

      - name: Install latest just release
        uses: taiki-e/install-action@v1
        with:
          tool: just

      - name: Lint
        run: |
          just fmt-check

  test-python:
    name: Test Python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |
          ./scripts/test_python

  test-rust:
    name: Test Rust
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/keywords/src/rust

    steps:
      - uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install latest just release
        uses: taiki-e/install-action@v1
        with:
          tool: just

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Install latest dprint release
        uses: taiki-e/install-action@v1
        with:
          tool: dprint

      - name: Test
        run: |
          just check

  test-nushell:
    name: Test Nushell
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install latest dprint release
        uses: taiki-e/install-action@v1
        with:
          tool: nu

      - name: Test
        run: |
          ./scripts/test_nushell

  test-fish:
    name: Test Fish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |
          ./scripts/test_fish
