name: Learn DSA (CI)

on:
  push:
    paths:
      -  src/dsa/**
      - .github/workflows/learn_dsa.yml
  pull_request:
    paths:
      -  src/dsa/**
      - .github/workflows/learn_dsa.yml

defaults:
  run:
    working-directory: src/dsa

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --user nox==2021.10.1

    - name: lint
      run: nox -s lint

    - name: test
      run: nox --session test-${{ matrix.python-version }}

    - name: Upload coverage report
      run: |
        nox -s coverage
        bash <(curl -s https://codecov.io/bash)
