name: Learn DSA (CI)

on:
  push:
    paths:
      -  src/dsa/**
      - .github/workflows/learn_dsa.yml
  pull_request:
    paths:
      -  src/dsa/**
      - .github/workflows/learn_dsa.yml

defaults:
  run:
    working-directory: src/dsa

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: taiki-e/install-action@just
    - uses: taiki-e/install-action@dprint
    - uses: taiki-e/install-action@v2
      with:
        tool: typos-cli

    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
      with:
        enable-cache: true

    - name: Setup dependencies
      run: just --yes setup

    - name: Check
      run: just check
