name: Pokedex SvelteKit (CI)

on:
  push:
    paths:
      -  src/pokedex-sveltekit/**
      - .github/workflows/pokedex_sveltekit.yml
  pull_request:
    paths:
      -  src/pokedex-sveltekit/**
      - .github/workflows/pokedex_sveltekit.yml

defaults:
  run:
    working-directory: src/pokedex-sveltekit

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dprint
        run: |
          curl --location https://github.com/dprint/dprint/releases/download/0.30.3/dprint-x86_64-unknown-linux-gnu.zip --output dprint.zip
          unzip dprint.zip
          cp dprint ~/.cargo/bin/
          dprint --version

      - name: Install latest just release
        uses: extractions/setup-just@v1

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: |
          pnpm i

      - name: Lint
        run: |
          just check
