name: Pokedex SvelteKit (CI)

on:
  push:
    paths:
      -  src/pokedex-sveltekit/**
      - .github/workflows/pokedex_sveltekit.yml
  pull_request:
    paths:
      -  src/pokedex-sveltekit/**
      - .github/workflows/pokedex_sveltekit.yml

defaults:
  run:
    working-directory: src/pokedex-sveltekit

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install latest dprint release
        uses: taiki-e/install-action@v1
        with:
          tool: dprint

      - name: Install latest just release
        uses: extractions/setup-just@v1

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: |
          pnpm i

      - name: Lint
        run: |
          just check
