name: Quiz SvelteKit CI

on:
  push:
    paths:
      -  src/quiz/sveltekit/**
      - .github/workflows/quiz_sveltekit.yml
  pull_request:
    paths:
      -  src/quiz/sveltekit/**
      - .github/workflows/quiz_sveltekit.yml

defaults:
  run:
    working-directory: src/quiz/sveltekit

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@dprint
      - uses: pnpm/action-setup@v2
        with:
          package_json_file: src/quiz/sveltekit/package.json

      - name: Install dependencies
        run: just setup

      - name: Lint
        # Build is required to generate types.
        run: |
          just build
          just fmt-check
          just lint

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # https://endoflife.date/nodejs
        node-version: [18.x, 20.x]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just

      - uses: pnpm/action-setup@v2
        with:
          package_json_file: src/quiz/sveltekit/package.json

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: pnpm
          cache-dependency-path: src/quiz/sveltekit/pnpm-lock.yaml

      - run: just setup
      - run: just test-unit

  test-e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - uses: pnpm/action-setup@v2
        with:
          package_json_file: src/quiz/sveltekit/package.json

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: pnpm
          cache-dependency-path: src/quiz/sveltekit/pnpm-lock.yaml

      - run: just setup

      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps

      - name: Run Playwright tests
        run: just test-all
