name: Quiz Vue CI

on:
  push:
    paths:
      -  src/quiz/vue/**
      - .github/workflows/quiz_vue.yml
  pull_request:
    paths:
      -  src/quiz/vue/**
      - .github/workflows/quiz_vue.yml

defaults:
  run:
    working-directory: src/quiz/vue

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@dprint
      - uses: pnpm/action-setup@v2
        with:
          package_json_file: src/quiz/vue/package.json

      - name: Install dependencies
        run: just setup

      - name: Lint
        run: |
          just fmt-check
          just lint

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # https://endoflife.date/nodejs
        node-version: [18.x, 20.x]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just

      - uses: pnpm/action-setup@v2
        with:
          package_json_file: src/quiz/vue/package.json

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: pnpm
          cache-dependency-path: src/quiz/vue/pnpm-lock.yaml

      - run: just setup
      - run: just test-unit

  test-e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - uses: pnpm/action-setup@v2
        with:
          package_json_file: src/quiz/vue/package.json

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: pnpm
          cache-dependency-path: src/quiz/vue/pnpm-lock.yaml

      - run: just setup

      - name: Cypress PNPM Patch
        run: cp pnpm-lock.yaml package-lock.json

      - name: Cypress
        uses: cypress-io/github-action@v4
        with:
          working-directory: src/quiz/vue
          install-command: echo
          build: pnpm run build
          start: npx vite --port 3333
          spec: |
            cypress/e2e/locale.cy.ts
            cypress/e2e/questionLimit.cy.ts
