name: Riddles Rust (CI)

on:
  push:
    paths:
      -  src/riddles/**
      - .github/workflows/riddles_rust.yml
  pull_request:
    paths:
      -  src/riddles/**
      - .github/workflows/riddles_rust.yml

defaults:
  run:
    working-directory: src/riddles/src/rust

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest

      - name: Install latest just release
        uses: taiki-e/install-action@v1
        with:
          tool: just

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: just check
