/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'IEosIcons:bubbleLoading': typeof import('~icons/eos-icons/bubble-loading')['default']
    'INoto:mechanicalArm': typeof import('~icons/noto/mechanical-arm')['default']
    'INoto:partyPopper': typeof import('~icons/noto/party-popper')['default']
    'INoto:sadButRelievedFace': typeof import('~icons/noto/sad-but-relieved-face')['default']
    'IPh:handWaving': typeof import('~icons/ph/hand-waving')['default']
    'ITabler:language': typeof import('~icons/tabler/language')['default']
    'ITabler:menu2': typeof import('~icons/tabler/menu2')['default']
    'ITabler:moodSad': typeof import('~icons/tabler/mood-sad')['default']
    'ITabler:x': typeof import('~icons/tabler/x')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    QuestionBox: typeof import('./src/components/QuestionBox.vue')['default']
    QuestionStatus: typeof import('./src/components/QuestionStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
